name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Greetings user! Thanks for being here! (v:'
        pr-message: 'Thanks for pulling a request! It will be implemented in a near future. Stay tuned!'
